

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using AppFramework.ApplicationLayer.Assemblers;
using Telerik.OpenAccess;
using KMUH.EduForm.ApplicationLayer.DTO;

namespace KMUH.EduForm.ApplicationLayer.Assemblers
{
}
#pragma warning restore 1591

