

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Dynamic;
using System.Linq.Expressions;
using System.Collections;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Telerik.OpenAccess;
using AppFramework.ApplicationLayer.Services;
using KMUH.EduForm.ApplicationLayer.Assemblers;
using KMUH.EduForm.ApplicationLayer.DTO;
using KMUH.EduForm.Infrastructure.Data.Repositories;

namespace KMUH.EduForm.ApplicationLayer.Services
{
}
#pragma warning restore 1591

