//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMU.EduActivity.ApConnService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDBReturnCollect", Namespace="http://KMUGService/GetDBConnection")]
    [System.SerializableAttribute()]
    public partial class GetDBReturnCollect : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConnectionStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ConnGetTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HospCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConnectionString {
            get {
                return this.ConnectionStringField;
            }
            set {
                if ((object.ReferenceEquals(this.ConnectionStringField, value) != true)) {
                    this.ConnectionStringField = value;
                    this.RaisePropertyChanged("ConnectionString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime ConnGetTime {
            get {
                return this.ConnGetTimeField;
            }
            set {
                if ((this.ConnGetTimeField.Equals(value) != true)) {
                    this.ConnGetTimeField = value;
                    this.RaisePropertyChanged("ConnGetTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string HospCode {
            get {
                return this.HospCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HospCodeField, value) != true)) {
                    this.HospCodeField = value;
                    this.RaisePropertyChanged("HospCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ClientIP {
            get {
                return this.ClientIPField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIPField, value) != true)) {
                    this.ClientIPField = value;
                    this.RaisePropertyChanged("ClientIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidatePWDReturnCollect", Namespace="http://KMUGService/ValidatePWD")]
    [System.SerializableAttribute()]
    public partial class ValidatePWDReturnCollect : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ValidateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private KMU.EduActivity.ApConnService.EnumColReturnAuthPasswordLevel AuthLevelField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckResult {
            get {
                return this.CheckResultField;
            }
            set {
                if ((this.CheckResultField.Equals(value) != true)) {
                    this.CheckResultField = value;
                    this.RaisePropertyChanged("CheckResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ValidateDateTime {
            get {
                return this.ValidateDateTimeField;
            }
            set {
                if ((this.ValidateDateTimeField.Equals(value) != true)) {
                    this.ValidateDateTimeField = value;
                    this.RaisePropertyChanged("ValidateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string AuthMessage {
            get {
                return this.AuthMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthMessageField, value) != true)) {
                    this.AuthMessageField = value;
                    this.RaisePropertyChanged("AuthMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public KMU.EduActivity.ApConnService.EnumColReturnAuthPasswordLevel AuthLevel {
            get {
                return this.AuthLevelField;
            }
            set {
                if ((this.AuthLevelField.Equals(value) != true)) {
                    this.AuthLevelField = value;
                    this.RaisePropertyChanged("AuthLevel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumCol.ReturnAuthPasswordLevel", Namespace="http://schemas.datacontract.org/2004/07/KMUGService.SystemAPI.StructureClass")]
    public enum EnumColReturnAuthPasswordLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuthFail = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LV1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LV2 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumCol.EnumResetPasswordType", Namespace="http://schemas.datacontract.org/2004/07/KMUGService.SystemAPI.StructureClass")]
    public enum EnumColEnumResetPasswordType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultReset = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailRule = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordChangeReturnCollect", Namespace="http://KMUGService/PasswordChange")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KMU.EduActivity.ApConnService.PasswordResetReturnCollect))]
    public partial class PasswordChangeReturnCollect : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsChangeDoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShowMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsChangeDone {
            get {
                return this.IsChangeDoneField;
            }
            set {
                if ((this.IsChangeDoneField.Equals(value) != true)) {
                    this.IsChangeDoneField = value;
                    this.RaisePropertyChanged("IsChangeDone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShowMessage {
            get {
                return this.ShowMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ShowMessageField, value) != true)) {
                    this.ShowMessageField = value;
                    this.RaisePropertyChanged("ShowMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemMessage {
            get {
                return this.SystemMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemMessageField, value) != true)) {
                    this.SystemMessageField = value;
                    this.RaisePropertyChanged("SystemMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PasswordResetReturnCollect", Namespace="http://KMUGService/PasswordReset")]
    [System.SerializableAttribute()]
    public partial class PasswordResetReturnCollect : KMU.EduActivity.ApConnService.PasswordChangeReturnCollect {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpireDateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailTo {
            get {
                return this.EmailToField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailToField, value) != true)) {
                    this.EmailToField = value;
                    this.RaisePropertyChanged("EmailTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpireDateTime {
            get {
                return this.ExpireDateTimeField;
            }
            set {
                if ((this.ExpireDateTimeField.Equals(value) != true)) {
                    this.ExpireDateTimeField = value;
                    this.RaisePropertyChanged("ExpireDateTime");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumCol.EnumEncryptType", Namespace="http://schemas.datacontract.org/2004/07/KMUGService.SystemAPI.StructureClass")]
    public enum EnumColEnumEncryptType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MD5 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHA1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHA256 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHA512 = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApConnService.IGetDBConnMethod")]
    public interface IGetDBConnMethod {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDBConnMethod/GetDBConnectionWithAuto", ReplyAction="http://tempuri.org/IGetDBConnMethod/GetDBConnectionWithAutoResponse")]
        KMU.EduActivity.ApConnService.GetDBReturnCollect GetDBConnectionWithAuto(string ServerName, string ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGetDBConnMethod/GetDBConnectionWithHospCode", ReplyAction="http://tempuri.org/IGetDBConnMethod/GetDBConnectionWithHospCodeResponse")]
        KMU.EduActivity.ApConnService.GetDBReturnCollect GetDBConnectionWithHospCode(string Hospital, string ServerName, string ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGetDBConnMethodChannel : KMU.EduActivity.ApConnService.IGetDBConnMethod, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDBConnMethodClient : System.ServiceModel.ClientBase<KMU.EduActivity.ApConnService.IGetDBConnMethod>, KMU.EduActivity.ApConnService.IGetDBConnMethod {
        
        public GetDBConnMethodClient() {
        }
        
        public GetDBConnMethodClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetDBConnMethodClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDBConnMethodClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetDBConnMethodClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KMU.EduActivity.ApConnService.GetDBReturnCollect GetDBConnectionWithAuto(string ServerName, string ID) {
            return base.Channel.GetDBConnectionWithAuto(ServerName, ID);
        }
        
        public KMU.EduActivity.ApConnService.GetDBReturnCollect GetDBConnectionWithHospCode(string Hospital, string ServerName, string ID) {
            return base.Channel.GetDBConnectionWithHospCode(Hospital, ServerName, ID);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApConnService.ICheckPwdMethod")]
    public interface ICheckPwdMethod {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckPwdMethod/CheckPasswordWithEncryption", ReplyAction="http://tempuri.org/ICheckPwdMethod/CheckPasswordWithEncryptionResponse")]
        KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPasswordWithEncryption(string UserId, string EncryptionPWD, string AuthPoing, string LoginIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckPwdMethod/CheckPassword", ReplyAction="http://tempuri.org/ICheckPwdMethod/CheckPasswordResponse")]
        KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPassword(string UserId, string PWD, string AuthPoing, string LoginIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckPwdMethod/CheckPasswordLv3", ReplyAction="http://tempuri.org/ICheckPwdMethod/CheckPasswordLv3Response")]
        KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPasswordLv3(string UserId, string PWD, string AuthPoing, string LoginIP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckPwdMethod/CheckPasswordTMS", ReplyAction="http://tempuri.org/ICheckPwdMethod/CheckPasswordTMSResponse")]
        KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPasswordTMS(string UserId, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICheckPwdMethod/CheckPwd", ReplyAction="http://tempuri.org/ICheckPwdMethod/CheckPwdResponse")]
        KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPwd(string UserId, string PWD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckPwdMethodChannel : KMU.EduActivity.ApConnService.ICheckPwdMethod, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckPwdMethodClient : System.ServiceModel.ClientBase<KMU.EduActivity.ApConnService.ICheckPwdMethod>, KMU.EduActivity.ApConnService.ICheckPwdMethod {
        
        public CheckPwdMethodClient() {
        }
        
        public CheckPwdMethodClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckPwdMethodClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckPwdMethodClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckPwdMethodClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPasswordWithEncryption(string UserId, string EncryptionPWD, string AuthPoing, string LoginIP) {
            return base.Channel.CheckPasswordWithEncryption(UserId, EncryptionPWD, AuthPoing, LoginIP);
        }
        
        public KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPassword(string UserId, string PWD, string AuthPoing, string LoginIP) {
            return base.Channel.CheckPassword(UserId, PWD, AuthPoing, LoginIP);
        }
        
        public KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPasswordLv3(string UserId, string PWD, string AuthPoing, string LoginIP) {
            return base.Channel.CheckPasswordLv3(UserId, PWD, AuthPoing, LoginIP);
        }
        
        public KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPasswordTMS(string UserId, string PWD) {
            return base.Channel.CheckPasswordTMS(UserId, PWD);
        }
        
        public KMU.EduActivity.ApConnService.ValidatePWDReturnCollect CheckPwd(string UserId, string PWD) {
            return base.Channel.CheckPwd(UserId, PWD);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApConnService.IModifyPasswordMethod")]
    public interface IModifyPasswordMethod {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModifyPasswordMethod/PasswordReset", ReplyAction="http://tempuri.org/IModifyPasswordMethod/PasswordResetResponse")]
        KMU.EduActivity.ApConnService.PasswordResetReturnCollect PasswordReset(string employeeID, string userTaiwanID, System.DateTime userBirthday, string userIP, string changePoint, KMU.EduActivity.ApConnService.EnumColEnumResetPasswordType resetType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IModifyPasswordMethod/ChangePassword", ReplyAction="http://tempuri.org/IModifyPasswordMethod/ChangePasswordResponse")]
        KMU.EduActivity.ApConnService.PasswordChangeReturnCollect ChangePassword(string employeeID, string oldPasswordLV2, string newPasswordLV1, string newPasswordLV2, string userIP, string changePoint, KMU.EduActivity.ApConnService.EnumColEnumEncryptType encrypype, bool isAlreadyEncryptPassword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IModifyPasswordMethodChannel : KMU.EduActivity.ApConnService.IModifyPasswordMethod, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ModifyPasswordMethodClient : System.ServiceModel.ClientBase<KMU.EduActivity.ApConnService.IModifyPasswordMethod>, KMU.EduActivity.ApConnService.IModifyPasswordMethod {
        
        public ModifyPasswordMethodClient() {
        }
        
        public ModifyPasswordMethodClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ModifyPasswordMethodClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModifyPasswordMethodClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ModifyPasswordMethodClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public KMU.EduActivity.ApConnService.PasswordResetReturnCollect PasswordReset(string employeeID, string userTaiwanID, System.DateTime userBirthday, string userIP, string changePoint, KMU.EduActivity.ApConnService.EnumColEnumResetPasswordType resetType) {
            return base.Channel.PasswordReset(employeeID, userTaiwanID, userBirthday, userIP, changePoint, resetType);
        }
        
        public KMU.EduActivity.ApConnService.PasswordChangeReturnCollect ChangePassword(string employeeID, string oldPasswordLV2, string newPasswordLV1, string newPasswordLV2, string userIP, string changePoint, KMU.EduActivity.ApConnService.EnumColEnumEncryptType encrypype, bool isAlreadyEncryptPassword) {
            return base.Channel.ChangePassword(employeeID, oldPasswordLV2, newPasswordLV1, newPasswordLV2, userIP, changePoint, encrypype, isAlreadyEncryptPassword);
        }
    }
}
