#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class AuthMenu
	{
		private int _menuID;
		public virtual int MenuID
		{
			get
			{
				return this._menuID;
			}
			set
			{
				this._menuID = value;
			}
		}
		
		private string _authID;
		public virtual string AuthID
		{
			get
			{
				return this._authID;
			}
			set
			{
				this._authID = value;
			}
		}
		
		private string _authType;
		public virtual string AuthType
		{
			get
			{
				return this._authType;
			}
			set
			{
				this._authType = value;
			}
		}
		
		private DateTime? _enableTime;
		public virtual DateTime? EnableTime
		{
			get
			{
				return this._enableTime;
			}
			set
			{
				this._enableTime = value;
			}
		}
		
	}
}
#pragma warning restore 1591
