#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class AutoEduFormTemplateList
	{
		private string _autoFTListID;
		public virtual string AutoFTListID
		{
			get
			{
				return this._autoFTListID;
			}
			set
			{
				this._autoFTListID = value;
			}
		}
		
		private string _jobCode;
		public virtual string JobCode
		{
			get
			{
				return this._jobCode;
			}
			set
			{
				this._jobCode = value;
			}
		}
		
		private int _tEMPLATE_ID;
		public virtual int TEMPLATE_ID
		{
			get
			{
				return this._tEMPLATE_ID;
			}
			set
			{
				this._tEMPLATE_ID = value;
			}
		}
		
		private string _settingName;
		public virtual string SettingName
		{
			get
			{
				return this._settingName;
			}
			set
			{
				this._settingName = value;
			}
		}
		
		private string _des;
		public virtual string Des
		{
			get
			{
				return this._des;
			}
			set
			{
				this._des = value;
			}
		}
		
		private bool? _eachStudent;
		public virtual bool? EachStudent
		{
			get
			{
				return this._eachStudent;
			}
			set
			{
				this._eachStudent = value;
			}
		}
		
		private string _dateShiftType;
		public virtual string DateShiftType
		{
			get
			{
				return this._dateShiftType;
			}
			set
			{
				this._dateShiftType = value;
			}
		}
		
		private int? _dateShift;
		public virtual int? DateShift
		{
			get
			{
				return this._dateShift;
			}
			set
			{
				this._dateShift = value;
			}
		}
		
		private bool? _multiTarget;
		public virtual bool? MultiTarget
		{
			get
			{
				return this._multiTarget;
			}
			set
			{
				this._multiTarget = value;
			}
		}
		
		private string _teacherType;
		public virtual string TeacherType
		{
			get
			{
				return this._teacherType;
			}
			set
			{
				this._teacherType = value;
			}
		}
		
		private int? _sendFloor;
		public virtual int? SendFloor
		{
			get
			{
				return this._sendFloor;
			}
			set
			{
				this._sendFloor = value;
			}
		}
		
		private string _creater;
		public virtual string Creater
		{
			get
			{
				return this._creater;
			}
			set
			{
				this._creater = value;
			}
		}
		
		private string _sendOrderSetting;
		public virtual string SendOrderSetting
		{
			get
			{
				return this._sendOrderSetting;
			}
			set
			{
				this._sendOrderSetting = value;
			}
		}
		
		private string _eduYear;
		public virtual string EduYear
		{
			get
			{
				return this._eduYear;
			}
			set
			{
				this._eduYear = value;
			}
		}
		
		private DateTime? _sdate;
		public virtual DateTime? Sdate
		{
			get
			{
				return this._sdate;
			}
			set
			{
				this._sdate = value;
			}
		}
		
		private DateTime? _edate;
		public virtual DateTime? Edate
		{
			get
			{
				return this._edate;
			}
			set
			{
				this._edate = value;
			}
		}
		
	}
}
#pragma warning restore 1591
