#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class AutoEduFormTemplateExcept
	{
		private string _autoFTListID;
		public virtual string AutoFTListID
		{
			get
			{
				return this._autoFTListID;
			}
			set
			{
				this._autoFTListID = value;
			}
		}
		
		private string _exceptType;
		public virtual string ExceptType
		{
			get
			{
				return this._exceptType;
			}
			set
			{
				this._exceptType = value;
			}
		}
		
		private string _exceptKey;
		public virtual string ExceptKey
		{
			get
			{
				return this._exceptKey;
			}
			set
			{
				this._exceptKey = value;
			}
		}
		
	}
}
#pragma warning restore 1591
