#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class DepSecDatum
	{
		private string _emp_Code;
		public virtual string Emp_Code
		{
			get
			{
				return this._emp_Code;
			}
			set
			{
				this._emp_Code = value;
			}
		}
		
		private string _dEPT_CODE;
		public virtual string DEPT_CODE
		{
			get
			{
				return this._dEPT_CODE;
			}
			set
			{
				this._dEPT_CODE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
