#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class EduActTopic
	{
		private string _eduActTopicID;
		public virtual string EduActTopicID
		{
			get
			{
				return this._eduActTopicID;
			}
			set
			{
				this._eduActTopicID = value;
			}
		}
		
		private string _eduActTopicCode;
		public virtual string EduActTopicCode
		{
			get
			{
				return this._eduActTopicCode;
			}
			set
			{
				this._eduActTopicCode = value;
			}
		}
		
		private string _eduActTopicName;
		public virtual string EduActTopicName
		{
			get
			{
				return this._eduActTopicName;
			}
			set
			{
				this._eduActTopicName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
