#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class EduFormTemplateTarget
	{
		private string _roleType;
		public virtual string RoleType
		{
			get
			{
				return this._roleType;
			}
			set
			{
				this._roleType = value;
			}
		}
		
		private DateTime? _expireDate;
		public virtual DateTime? ExpireDate
		{
			get
			{
				return this._expireDate;
			}
			set
			{
				this._expireDate = value;
			}
		}
		
		private int _subTEMPLATE_ID;
		public virtual int SubTEMPLATE_ID
		{
			get
			{
				return this._subTEMPLATE_ID;
			}
			set
			{
				this._subTEMPLATE_ID = value;
			}
		}
		
		private string _fTTargetID;
		public virtual string FTTargetID
		{
			get
			{
				return this._fTTargetID;
			}
			set
			{
				this._fTTargetID = value;
			}
		}
		
		private string _fTListID;
		public virtual string FTListID
		{
			get
			{
				return this._fTListID;
			}
			set
			{
				this._fTListID = value;
			}
		}
		
		private string _userDefineTargetID;
		public virtual string UserDefineTargetID
		{
			get
			{
				return this._userDefineTargetID;
			}
			set
			{
				this._userDefineTargetID = value;
			}
		}
		
		private string _teacherType;
		public virtual string TeacherType
		{
			get
			{
				return this._teacherType;
			}
			set
			{
				this._teacherType = value;
			}
		}
		
	}
}
#pragma warning restore 1591
