#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class EduTermFormReqTemplateDet
	{
		private int _detID;
		public virtual int DetID
		{
			get
			{
				return this._detID;
			}
			set
			{
				this._detID = value;
			}
		}
		
		private int _templateID;
		public virtual int TemplateID
		{
			get
			{
				return this._templateID;
			}
			set
			{
				this._templateID = value;
			}
		}
		
		private string _reqType;
		public virtual string ReqType
		{
			get
			{
				return this._reqType;
			}
			set
			{
				this._reqType = value;
			}
		}
		
		private int _reqID;
		public virtual int ReqID
		{
			get
			{
				return this._reqID;
			}
			set
			{
				this._reqID = value;
			}
		}
		
		private int _reqCount;
		public virtual int ReqCount
		{
			get
			{
				return this._reqCount;
			}
			set
			{
				this._reqCount = value;
			}
		}
		
		private bool _needPass;
		public virtual bool NeedPass
		{
			get
			{
				return this._needPass;
			}
			set
			{
				this._needPass = value;
			}
		}
		
		private EduTermFormReqTemplate _eduTermFormReqTemplate;
		public virtual EduTermFormReqTemplate EduTermFormReqTemplate
		{
			get
			{
				return this._eduTermFormReqTemplate;
			}
			set
			{
				this._eduTermFormReqTemplate = value;
			}
		}
		
	}
}
#pragma warning restore 1591
