#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class EduTeam
	{
		private string _eduTeamCode;
		public virtual string EduTeamCode
		{
			get
			{
				return this._eduTeamCode;
			}
			set
			{
				this._eduTeamCode = value;
			}
		}
		
		private string _teamMemberType;
		public virtual string TeamMemberType
		{
			get
			{
				return this._teamMemberType;
			}
			set
			{
				this._teamMemberType = value;
			}
		}
		
		private Char _status;
		public virtual Char Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private string _parentEduTeamCode;
		public virtual string ParentEduTeamCode
		{
			get
			{
				return this._parentEduTeamCode;
			}
			set
			{
				this._parentEduTeamCode = value;
			}
		}
		
		private string _eduTeamName;
		public virtual string EduTeamName
		{
			get
			{
				return this._eduTeamName;
			}
			set
			{
				this._eduTeamName = value;
			}
		}
		
		private int? _displayOrder;
		public virtual int? DisplayOrder
		{
			get
			{
				return this._displayOrder;
			}
			set
			{
				this._displayOrder = value;
			}
		}
		
		private string _jobCode;
		public virtual string JobCode
		{
			get
			{
				return this._jobCode;
			}
			set
			{
				this._jobCode = value;
			}
		}
		
		private EduTeam _eduTeam1;
		public virtual EduTeam EduTeam1
		{
			get
			{
				return this._eduTeam1;
			}
			set
			{
				this._eduTeam1 = value;
			}
		}
		
		private IList<EduTeamRundown> _eduTeamRundowns = new List<EduTeamRundown>();
		public virtual IList<EduTeamRundown> EduTeamRundowns
		{
			get
			{
				return this._eduTeamRundowns;
			}
		}
		
		private IList<EduTeamMember> _eduTeamMembers = new List<EduTeamMember>();
		public virtual IList<EduTeamMember> EduTeamMembers
		{
			get
			{
				return this._eduTeamMembers;
			}
		}
		
		private IList<EduTeam> _eduTeams = new List<EduTeam>();
		public virtual IList<EduTeam> EduTeams
		{
			get
			{
				return this._eduTeams;
			}
		}
		
	}
}
#pragma warning restore 1591
