#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class EduTeamRundown
	{
		private string _eduTeamStopID;
		public virtual string EduTeamStopID
		{
			get
			{
				return this._eduTeamStopID;
			}
			set
			{
				this._eduTeamStopID = value;
			}
		}
		
		private string _eduTermID;
		public virtual string EduTermID
		{
			get
			{
				return this._eduTermID;
			}
			set
			{
				this._eduTermID = value;
			}
		}
		
		private string _eduTeamCode;
		public virtual string EduTeamCode
		{
			get
			{
				return this._eduTeamCode;
			}
			set
			{
				this._eduTeamCode = value;
			}
		}
		
		private DateTime _dateFrom;
		public virtual DateTime DateFrom
		{
			get
			{
				return this._dateFrom;
			}
			set
			{
				this._dateFrom = value;
			}
		}
		
		private DateTime _dateTo;
		public virtual DateTime DateTo
		{
			get
			{
				return this._dateTo;
			}
			set
			{
				this._dateTo = value;
			}
		}
		
		private EduTeam _eduTeam;
		public virtual EduTeam EduTeam
		{
			get
			{
				return this._eduTeam;
			}
			set
			{
				this._eduTeam = value;
			}
		}
		
		private EduTerm _eduTerm;
		public virtual EduTerm EduTerm
		{
			get
			{
				return this._eduTerm;
			}
			set
			{
				this._eduTerm = value;
			}
		}
		
	}
}
#pragma warning restore 1591
