#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class EduTerm
	{
		private string _eduTermID;
		public virtual string EduTermID
		{
			get
			{
				return this._eduTermID;
			}
			set
			{
				this._eduTermID = value;
			}
		}
		
		private string _eduStopCode;
		public virtual string EduStopCode
		{
			get
			{
				return this._eduStopCode;
			}
			set
			{
				this._eduStopCode = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _depCode;
		public virtual string DepCode
		{
			get
			{
				return this._depCode;
			}
			set
			{
				this._depCode = value;
			}
		}
		
		private string _nStation;
		public virtual string NStation
		{
			get
			{
				return this._nStation;
			}
			set
			{
				this._nStation = value;
			}
		}
		
		private string _corchID;
		public virtual string CorchID
		{
			get
			{
				return this._corchID;
			}
			set
			{
				this._corchID = value;
			}
		}
		
		private DateTime _dateFrom;
		public virtual DateTime DateFrom
		{
			get
			{
				return this._dateFrom;
			}
			set
			{
				this._dateFrom = value;
			}
		}
		
		private DateTime _dateTo;
		public virtual DateTime DateTo
		{
			get
			{
				return this._dateTo;
			}
			set
			{
				this._dateTo = value;
			}
		}
		
		private System.Nullable<System.Char> _isClass;
		public virtual System.Nullable<System.Char> IsClass
		{
			get
			{
				return this._isClass;
			}
			set
			{
				this._isClass = value;
			}
		}
		
		private string _roundCode;
		public virtual string RoundCode
		{
			get
			{
				return this._roundCode;
			}
			set
			{
				this._roundCode = value;
			}
		}
		
		private System.Nullable<System.Char> _status;
		public virtual System.Nullable<System.Char> Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private string _des;
		public virtual string Des
		{
			get
			{
				return this._des;
			}
			set
			{
				this._des = value;
			}
		}
		
		private int _capacity;
		public virtual int Capacity
		{
			get
			{
				return this._capacity;
			}
			set
			{
				this._capacity = value;
			}
		}
		
		private string _memberType;
		public virtual string MemberType
		{
			get
			{
				return this._memberType;
			}
			set
			{
				this._memberType = value;
			}
		}
		
		private string _eduStopID;
		public virtual string EduStopID
		{
			get
			{
				return this._eduStopID;
			}
			set
			{
				this._eduStopID = value;
			}
		}
		
		private string _teacher;
		public virtual string Teacher
		{
			get
			{
				return this._teacher;
			}
			set
			{
				this._teacher = value;
			}
		}
		
		private string _eBM;
		public virtual string EBM
		{
			get
			{
				return this._eBM;
			}
			set
			{
				this._eBM = value;
			}
		}
		
		private string _creater;
		public virtual string Creater
		{
			get
			{
				return this._creater;
			}
			set
			{
				this._creater = value;
			}
		}
		
		private string _parentEduTermID;
		public virtual string ParentEduTermID
		{
			get
			{
				return this._parentEduTermID;
			}
			set
			{
				this._parentEduTermID = value;
			}
		}
		
		private string _jobCode;
		public virtual string JobCode
		{
			get
			{
				return this._jobCode;
			}
			set
			{
				this._jobCode = value;
			}
		}
		
		private System.Nullable<System.Char> _hospital;
		public virtual System.Nullable<System.Char> Hospital
		{
			get
			{
				return this._hospital;
			}
			set
			{
				this._hospital = value;
			}
		}
		
		private string _eduYear;
		public virtual string EduYear
		{
			get
			{
				return this._eduYear;
			}
			set
			{
				this._eduYear = value;
			}
		}
		
		private string _department;
		public virtual string Department
		{
			get
			{
				return this._department;
			}
			set
			{
				this._department = value;
			}
		}
		
		private bool _hasTeacher;
		public virtual bool HasTeacher
		{
			get
			{
				return this._hasTeacher;
			}
			set
			{
				this._hasTeacher = value;
			}
		}
		
		private bool _hasMember;
		public virtual bool HasMember
		{
			get
			{
				return this._hasMember;
			}
			set
			{
				this._hasMember = value;
			}
		}
		
		private string _schoolSeqNo2;
		public virtual string SchoolSeqNo2
		{
			get
			{
				return this._schoolSeqNo2;
			}
			set
			{
				this._schoolSeqNo2 = value;
			}
		}
		
		private string _schoolSeqNo1;
		public virtual string SchoolSeqNo1
		{
			get
			{
				return this._schoolSeqNo1;
			}
			set
			{
				this._schoolSeqNo1 = value;
			}
		}
		
		private EduTerm _eduTerm1;
		public virtual EduTerm EduTerm1
		{
			get
			{
				return this._eduTerm1;
			}
			set
			{
				this._eduTerm1 = value;
			}
		}
		
		private IList<EduTeamRundown> _eduTeamRundowns = new List<EduTeamRundown>();
		public virtual IList<EduTeamRundown> EduTeamRundowns
		{
			get
			{
				return this._eduTeamRundowns;
			}
		}
		
		private IList<EduTerm> _eduTerms = new List<EduTerm>();
		public virtual IList<EduTerm> EduTerms
		{
			get
			{
				return this._eduTerms;
			}
		}
		
	}
}
#pragma warning restore 1591
