#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class EduTeamMember
	{
		private string _eduTeamMemberID;
		public virtual string EduTeamMemberID
		{
			get
			{
				return this._eduTeamMemberID;
			}
			set
			{
				this._eduTeamMemberID = value;
			}
		}
		
		private string _eduTeamCode;
		public virtual string EduTeamCode
		{
			get
			{
				return this._eduTeamCode;
			}
			set
			{
				this._eduTeamCode = value;
			}
		}
		
		private string _memberCode;
		public virtual string MemberCode
		{
			get
			{
				return this._memberCode;
			}
			set
			{
				this._memberCode = value;
			}
		}
		
		private string _memberID;
		public virtual string MemberID
		{
			get
			{
				return this._memberID;
			}
			set
			{
				this._memberID = value;
			}
		}
		
		private string _tutor2;
		public virtual string Tutor2
		{
			get
			{
				return this._tutor2;
			}
			set
			{
				this._tutor2 = value;
			}
		}
		
		private string _tutor;
		public virtual string Tutor
		{
			get
			{
				return this._tutor;
			}
			set
			{
				this._tutor = value;
			}
		}
		
		private Member _member;
		public virtual Member Member
		{
			get
			{
				return this._member;
			}
			set
			{
				this._member = value;
			}
		}
		
		private EduTeam _eduTeam;
		public virtual EduTeam EduTeam
		{
			get
			{
				return this._eduTeam;
			}
			set
			{
				this._eduTeam = value;
			}
		}
		
	}
}
#pragma warning restore 1591
