#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class ElearningClass
	{
		private string _classID;
		public virtual string ClassID
		{
			get
			{
				return this._classID;
			}
			set
			{
				this._classID = value;
			}
		}
		
		private string _className;
		public virtual string ClassName
		{
			get
			{
				return this._className;
			}
			set
			{
				this._className = value;
			}
		}
		
		private bool _allowBooking;
		public virtual bool AllowBooking
		{
			get
			{
				return this._allowBooking;
			}
			set
			{
				this._allowBooking = value;
			}
		}
		
		private string _creater;
		public virtual string Creater
		{
			get
			{
				return this._creater;
			}
			set
			{
				this._creater = value;
			}
		}
		
		private DateTime? _createDate;
		public virtual DateTime? CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private DateTime? _sDate;
		public virtual DateTime? SDate
		{
			get
			{
				return this._sDate;
			}
			set
			{
				this._sDate = value;
			}
		}
		
		private DateTime? _eDate;
		public virtual DateTime? EDate
		{
			get
			{
				return this._eDate;
			}
			set
			{
				this._eDate = value;
			}
		}
		
		private string _status;
		public virtual string Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private IList<ElearningBooking> _elearningBookings = new List<ElearningBooking>();
		public virtual IList<ElearningBooking> ElearningBookings
		{
			get
			{
				return this._elearningBookings;
			}
		}
		
		private IList<ElearningItem> _elearningItems = new List<ElearningItem>();
		public virtual IList<ElearningItem> ElearningItems
		{
			get
			{
				return this._elearningItems;
			}
		}
		
	}
}
#pragma warning restore 1591
