#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class f_EduStopActScheduleResultSet0
	{
		private string _eduStopActScheduleID;
		public virtual string EduStopActScheduleID
		{
			get
			{
				return this._eduStopActScheduleID;
			}
			set
			{
				this._eduStopActScheduleID = value;
			}
		}
		
		private DateTime? _timeFrom;
		public virtual DateTime? TimeFrom
		{
			get
			{
				return this._timeFrom;
			}
			set
			{
				this._timeFrom = value;
			}
		}
		
		private DateTime? _timeto;
		public virtual DateTime? Timeto
		{
			get
			{
				return this._timeto;
			}
			set
			{
				this._timeto = value;
			}
		}
		
		private string _des;
		public virtual string Des
		{
			get
			{
				return this._des;
			}
			set
			{
				this._des = value;
			}
		}
		
		private string _actType;
		public virtual string ActType
		{
			get
			{
				return this._actType;
			}
			set
			{
				this._actType = value;
			}
		}
		
		private string _actTypeName;
		public virtual string ActTypeName
		{
			get
			{
				return this._actTypeName;
			}
			set
			{
				this._actTypeName = value;
			}
		}
		
		private string _eduActTopicCode;
		public virtual string EduActTopicCode
		{
			get
			{
				return this._eduActTopicCode;
			}
			set
			{
				this._eduActTopicCode = value;
			}
		}
		
		private string _eduActTopicName;
		public virtual string EduActTopicName
		{
			get
			{
				return this._eduActTopicName;
			}
			set
			{
				this._eduActTopicName = value;
			}
		}
		
		private string _eduStopCode;
		public virtual string EduStopCode
		{
			get
			{
				return this._eduStopCode;
			}
			set
			{
				this._eduStopCode = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _eduTermID;
		public virtual string EduTermID
		{
			get
			{
				return this._eduTermID;
			}
			set
			{
				this._eduTermID = value;
			}
		}
		
		private string _location;
		public virtual string Location
		{
			get
			{
				return this._location;
			}
			set
			{
				this._location = value;
			}
		}
		
		private string _eduActTopicID;
		public virtual string EduActTopicID
		{
			get
			{
				return this._eduActTopicID;
			}
			set
			{
				this._eduActTopicID = value;
			}
		}
		
		private string _actTypeDes;
		public virtual string ActTypeDes
		{
			get
			{
				return this._actTypeDes;
			}
			set
			{
				this._actTypeDes = value;
			}
		}
		
		private string _creater;
		public virtual string Creater
		{
			get
			{
				return this._creater;
			}
			set
			{
				this._creater = value;
			}
		}
		
		private string _lastModifier;
		public virtual string LastModifier
		{
			get
			{
				return this._lastModifier;
			}
			set
			{
				this._lastModifier = value;
			}
		}
		
		private string _actName;
		public virtual string ActName
		{
			get
			{
				return this._actName;
			}
			set
			{
				this._actName = value;
			}
		}
		
	}
}
#pragma warning restore 1591
