#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class FORM_INSTANCE_TARGET
	{
		private string _targetID;
		public virtual string TargetID
		{
			get
			{
				return this._targetID;
			}
			set
			{
				this._targetID = value;
			}
		}
		
		private int _iNSTANCE_ID;
		public virtual int INSTANCE_ID
		{
			get
			{
				return this._iNSTANCE_ID;
			}
			set
			{
				this._iNSTANCE_ID = value;
			}
		}
		
		private int? _targetOrder;
		public virtual int? TargetOrder
		{
			get
			{
				return this._targetOrder;
			}
			set
			{
				this._targetOrder = value;
			}
		}
		
		private System.Nullable<System.Char> _status;
		public virtual System.Nullable<System.Char> Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private string _targetType;
		public virtual string TargetType
		{
			get
			{
				return this._targetType;
			}
			set
			{
				this._targetType = value;
			}
		}
		
		private DateTime? _alertTime;
		public virtual DateTime? AlertTime
		{
			get
			{
				return this._alertTime;
			}
			set
			{
				this._alertTime = value;
			}
		}
		
		private string _targetSource;
		public virtual string TargetSource
		{
			get
			{
				return this._targetSource;
			}
			set
			{
				this._targetSource = value;
			}
		}
		
		private FORM_INSTANCE _fORM_INSTANCE;
		public virtual FORM_INSTANCE FORM_INSTANCE
		{
			get
			{
				return this._fORM_INSTANCE;
			}
			set
			{
				this._fORM_INSTANCE = value;
			}
		}
		
	}
}
#pragma warning restore 1591
