#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class HealTeachTime
	{
		private string _empCode;
		public virtual string EmpCode
		{
			get
			{
				return this._empCode;
			}
			set
			{
				this._empCode = value;
			}
		}
		
		private DateTime _dataDate;
		public virtual DateTime DataDate
		{
			get
			{
				return this._dataDate;
			}
			set
			{
				this._dataDate = value;
			}
		}
		
		private string _deptCode;
		public virtual string DeptCode
		{
			get
			{
				return this._deptCode;
			}
			set
			{
				this._deptCode = value;
			}
		}
		
		private string _actType;
		public virtual string ActType
		{
			get
			{
				return this._actType;
			}
			set
			{
				this._actType = value;
			}
		}
		
		private string _targetType;
		public virtual string TargetType
		{
			get
			{
				return this._targetType;
			}
			set
			{
				this._targetType = value;
			}
		}
		
		private decimal? _teachTime;
		public virtual decimal? TeachTime
		{
			get
			{
				return this._teachTime;
			}
			set
			{
				this._teachTime = value;
			}
		}
		
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _hospCode;
		public virtual string HospCode
		{
			get
			{
				return this._hospCode;
			}
			set
			{
				this._hospCode = value;
			}
		}
		
		private DateTime? _createTime;
		public virtual DateTime? CreateTime
		{
			get
			{
				return this._createTime;
			}
			set
			{
				this._createTime = value;
			}
		}
		
		private string _creater;
		public virtual string Creater
		{
			get
			{
				return this._creater;
			}
			set
			{
				this._creater = value;
			}
		}
		
	}
}
#pragma warning restore 1591
