#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class HealTeachTimeRate
	{
		private int _settingID;
		public virtual int SettingID
		{
			get
			{
				return this._settingID;
			}
			set
			{
				this._settingID = value;
			}
		}
		
		private string _actType;
		public virtual string ActType
		{
			get
			{
				return this._actType;
			}
			set
			{
				this._actType = value;
			}
		}
		
		private int? _rate1;
		public virtual int? Rate1
		{
			get
			{
				return this._rate1;
			}
			set
			{
				this._rate1 = value;
			}
		}
		
		private int? _rate2;
		public virtual int? Rate2
		{
			get
			{
				return this._rate2;
			}
			set
			{
				this._rate2 = value;
			}
		}
		
		private int? _weekLimit;
		public virtual int? WeekLimit
		{
			get
			{
				return this._weekLimit;
			}
			set
			{
				this._weekLimit = value;
			}
		}
		
	}
}
#pragma warning restore 1591
