#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class IKASA_Menu
	{
		private string _menuid;
		public virtual string Menuid
		{
			get
			{
				return this._menuid;
			}
			set
			{
				this._menuid = value;
			}
		}
		
		private string _menutext;
		public virtual string Menutext
		{
			get
			{
				return this._menutext;
			}
			set
			{
				this._menutext = value;
			}
		}
		
		private string _bgcolor;
		public virtual string Bgcolor
		{
			get
			{
				return this._bgcolor;
			}
			set
			{
				this._bgcolor = value;
			}
		}
		
		private string _fontcolor;
		public virtual string Fontcolor
		{
			get
			{
				return this._fontcolor;
			}
			set
			{
				this._fontcolor = value;
			}
		}
		
		private string _parentmenuid;
		public virtual string Parentmenuid
		{
			get
			{
				return this._parentmenuid;
			}
			set
			{
				this._parentmenuid = value;
			}
		}
		
		private string _hinttext;
		public virtual string Hinttext
		{
			get
			{
				return this._hinttext;
			}
			set
			{
				this._hinttext = value;
			}
		}
		
		private string _remark;
		public virtual string Remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				this._remark = value;
			}
		}
		
		private DateTime? _enabledate;
		public virtual DateTime? Enabledate
		{
			get
			{
				return this._enabledate;
			}
			set
			{
				this._enabledate = value;
			}
		}
		
		private DateTime? _disabledate;
		public virtual DateTime? Disabledate
		{
			get
			{
				return this._disabledate;
			}
			set
			{
				this._disabledate = value;
			}
		}
		
		private string _isshow;
		public virtual string Isshow
		{
			get
			{
				return this._isshow;
			}
			set
			{
				this._isshow = value;
			}
		}
		
		private string _frameurl;
		public virtual string Frameurl
		{
			get
			{
				return this._frameurl;
			}
			set
			{
				this._frameurl = value;
			}
		}
		
		private int? _displayorder;
		public virtual int? Displayorder
		{
			get
			{
				return this._displayorder;
			}
			set
			{
				this._displayorder = value;
			}
		}
		
	}
}
#pragma warning restore 1591
