#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class IKASA_ERCase_EvalDet
	{
		private int _evalID;
		public virtual int EvalID
		{
			get
			{
				return this._evalID;
			}
			set
			{
				this._evalID = value;
			}
		}
		
		private string _controlID;
		public virtual string ControlID
		{
			get
			{
				return this._controlID;
			}
			set
			{
				this._controlID = value;
			}
		}
		
		private string _controlValue;
		public virtual string ControlValue
		{
			get
			{
				return this._controlValue;
			}
			set
			{
				this._controlValue = value;
			}
		}
		
		private IKASA_ERCase_Eval _iKASA_ERCase_Eval;
		public virtual IKASA_ERCase_Eval IKASA_ERCase_Eval
		{
			get
			{
				return this._iKASA_ERCase_Eval;
			}
			set
			{
				this._iKASA_ERCase_Eval = value;
			}
		}
		
	}
}
#pragma warning restore 1591
