#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class IKASA_MenuParam
	{
		private string _menuid;
		public virtual string Menuid
		{
			get
			{
				return this._menuid;
			}
			set
			{
				this._menuid = value;
			}
		}
		
		private string _paramname;
		public virtual string Paramname
		{
			get
			{
				return this._paramname;
			}
			set
			{
				this._paramname = value;
			}
		}
		
		private string _paramvalue;
		public virtual string Paramvalue
		{
			get
			{
				return this._paramvalue;
			}
			set
			{
				this._paramvalue = value;
			}
		}
		
	}
}
#pragma warning restore 1591
