#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class LoginLog
	{
		private int _iD;
		public virtual int ID
		{
			get
			{
				return this._iD;
			}
			set
			{
				this._iD = value;
			}
		}
		
		private string _empCode;
		public virtual string EmpCode
		{
			get
			{
				return this._empCode;
			}
			set
			{
				this._empCode = value;
			}
		}
		
		private DateTime _loginTime;
		public virtual DateTime LoginTime
		{
			get
			{
				return this._loginTime;
			}
			set
			{
				this._loginTime = value;
			}
		}
		
		private bool _isSuccess;
		public virtual bool IsSuccess
		{
			get
			{
				return this._isSuccess;
			}
			set
			{
				this._isSuccess = value;
			}
		}
		
		private string _loginIP;
		public virtual string LoginIP
		{
			get
			{
				return this._loginIP;
			}
			set
			{
				this._loginIP = value;
			}
		}
		
	}
}
#pragma warning restore 1591
