#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class MonthlyTeachPointCalcDatum
	{
		private DateTime _calDate;
		public virtual DateTime CalDate
		{
			get
			{
				return this._calDate;
			}
			set
			{
				this._calDate = value;
			}
		}
		
		private string _empCode;
		public virtual string EmpCode
		{
			get
			{
				return this._empCode;
			}
			set
			{
				this._empCode = value;
			}
		}
		
		private DateTime _sdate;
		public virtual DateTime Sdate
		{
			get
			{
				return this._sdate;
			}
			set
			{
				this._sdate = value;
			}
		}
		
		private DateTime _edate;
		public virtual DateTime Edate
		{
			get
			{
				return this._edate;
			}
			set
			{
				this._edate = value;
			}
		}
		
		private bool _isLatest;
		public virtual bool IsLatest
		{
			get
			{
				return this._isLatest;
			}
			set
			{
				this._isLatest = value;
			}
		}
		
		private string _param0;
		public virtual string Param0
		{
			get
			{
				return this._param0;
			}
			set
			{
				this._param0 = value;
			}
		}
		
		private string _param1;
		public virtual string Param1
		{
			get
			{
				return this._param1;
			}
			set
			{
				this._param1 = value;
			}
		}
		
		private string _param2;
		public virtual string Param2
		{
			get
			{
				return this._param2;
			}
			set
			{
				this._param2 = value;
			}
		}
		
		private string _param3;
		public virtual string Param3
		{
			get
			{
				return this._param3;
			}
			set
			{
				this._param3 = value;
			}
		}
		
		private string _param4;
		public virtual string Param4
		{
			get
			{
				return this._param4;
			}
			set
			{
				this._param4 = value;
			}
		}
		
		private string _param5;
		public virtual string Param5
		{
			get
			{
				return this._param5;
			}
			set
			{
				this._param5 = value;
			}
		}
		
		private string _param6;
		public virtual string Param6
		{
			get
			{
				return this._param6;
			}
			set
			{
				this._param6 = value;
			}
		}
		
		private string _param7;
		public virtual string Param7
		{
			get
			{
				return this._param7;
			}
			set
			{
				this._param7 = value;
			}
		}
		
		private string _param8;
		public virtual string Param8
		{
			get
			{
				return this._param8;
			}
			set
			{
				this._param8 = value;
			}
		}
		
		private string _param9;
		public virtual string Param9
		{
			get
			{
				return this._param9;
			}
			set
			{
				this._param9 = value;
			}
		}
		
		private string _param10;
		public virtual string Param10
		{
			get
			{
				return this._param10;
			}
			set
			{
				this._param10 = value;
			}
		}
		
		private string _param11;
		public virtual string Param11
		{
			get
			{
				return this._param11;
			}
			set
			{
				this._param11 = value;
			}
		}
		
		private string _param12;
		public virtual string Param12
		{
			get
			{
				return this._param12;
			}
			set
			{
				this._param12 = value;
			}
		}
		
		private string _param13;
		public virtual string Param13
		{
			get
			{
				return this._param13;
			}
			set
			{
				this._param13 = value;
			}
		}
		
	}
}
#pragma warning restore 1591
