#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class News_Attachment
	{
		private int _attachmentID;
		public virtual int AttachmentID
		{
			get
			{
				return this._attachmentID;
			}
			set
			{
				this._attachmentID = value;
			}
		}
		
		private string _nEWID;
		public virtual string NEWID
		{
			get
			{
				return this._nEWID;
			}
			set
			{
				this._nEWID = value;
			}
		}
		
		private string _attachmentName;
		public virtual string AttachmentName
		{
			get
			{
				return this._attachmentName;
			}
			set
			{
				this._attachmentName = value;
			}
		}
		
		private byte[] _attachment;
		public virtual byte[] Attachment
		{
			get
			{
				return this._attachment;
			}
			set
			{
				this._attachment = value;
			}
		}
		
		private News _news;
		public virtual News News
		{
			get
			{
				return this._news;
			}
			set
			{
				this._news = value;
			}
		}
		
	}
}
#pragma warning restore 1591
