#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class PassPortStudentApplicationItem
	{
		private int _applicationID;
		public virtual int ApplicationID
		{
			get
			{
				return this._applicationID;
			}
			set
			{
				this._applicationID = value;
			}
		}
		
		private int? _itemCode;
		public virtual int? ItemCode
		{
			get
			{
				return this._itemCode;
			}
			set
			{
				this._itemCode = value;
			}
		}
		
		private string _applicationMemberNumber;
		public virtual string ApplicationMemberNumber
		{
			get
			{
				return this._applicationMemberNumber;
			}
			set
			{
				this._applicationMemberNumber = value;
			}
		}
		
		private int? _checkOrder;
		public virtual int? CheckOrder
		{
			get
			{
				return this._checkOrder;
			}
			set
			{
				this._checkOrder = value;
			}
		}
		
		private string _designationTeacherNumber;
		public virtual string DesignationTeacherNumber
		{
			get
			{
				return this._designationTeacherNumber;
			}
			set
			{
				this._designationTeacherNumber = value;
			}
		}
		
		private string _implementPlace;
		public virtual string ImplementPlace
		{
			get
			{
				return this._implementPlace;
			}
			set
			{
				this._implementPlace = value;
			}
		}
		
		private DateTime? _implementDate;
		public virtual DateTime? ImplementDate
		{
			get
			{
				return this._implementDate;
			}
			set
			{
				this._implementDate = value;
			}
		}
		
		private DateTime? _applicationDate;
		public virtual DateTime? ApplicationDate
		{
			get
			{
				return this._applicationDate;
			}
			set
			{
				this._applicationDate = value;
			}
		}
		
		private bool? _isFinalCheck;
		public virtual bool? IsFinalCheck
		{
			get
			{
				return this._isFinalCheck;
			}
			set
			{
				this._isFinalCheck = value;
			}
		}
		
		private bool? _checkResult;
		public virtual bool? CheckResult
		{
			get
			{
				return this._checkResult;
			}
			set
			{
				this._checkResult = value;
			}
		}
		
		private string _checkStatus;
		public virtual string CheckStatus
		{
			get
			{
				return this._checkStatus;
			}
			set
			{
				this._checkStatus = value;
			}
		}
		
		private DateTime? _checkDate;
		public virtual DateTime? CheckDate
		{
			get
			{
				return this._checkDate;
			}
			set
			{
				this._checkDate = value;
			}
		}
		
		private string _studentRemark;
		public virtual string StudentRemark
		{
			get
			{
				return this._studentRemark;
			}
			set
			{
				this._studentRemark = value;
			}
		}
		
		private string _implementObject;
		public virtual string ImplementObject
		{
			get
			{
				return this._implementObject;
			}
			set
			{
				this._implementObject = value;
			}
		}
		
		private string _caseHistoryNumber;
		public virtual string CaseHistoryNumber
		{
			get
			{
				return this._caseHistoryNumber;
			}
			set
			{
				this._caseHistoryNumber = value;
			}
		}
		
		private string _teacherRemark;
		public virtual string TeacherRemark
		{
			get
			{
				return this._teacherRemark;
			}
			set
			{
				this._teacherRemark = value;
			}
		}
		
		private string _jobCode;
		public virtual string JobCode
		{
			get
			{
				return this._jobCode;
			}
			set
			{
				this._jobCode = value;
			}
		}
		
		private PassPortCheckItem _passPortCheckItem;
		public virtual PassPortCheckItem PassPortCheckItem
		{
			get
			{
				return this._passPortCheckItem;
			}
			set
			{
				this._passPortCheckItem = value;
			}
		}
		
	}
}
#pragma warning restore 1591
