#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class RecordInsDet
	{
		private string _instanceID;
		public virtual string InstanceID
		{
			get
			{
				return this._instanceID;
			}
			set
			{
				this._instanceID = value;
			}
		}
		
		private string _controlID;
		public virtual string ControlID
		{
			get
			{
				return this._controlID;
			}
			set
			{
				this._controlID = value;
			}
		}
		
		private string _controlValue;
		public virtual string ControlValue
		{
			get
			{
				return this._controlValue;
			}
			set
			{
				this._controlValue = value;
			}
		}
		
		private RecordInstance _recordInstance;
		public virtual RecordInstance RecordInstance
		{
			get
			{
				return this._recordInstance;
			}
			set
			{
				this._recordInstance = value;
			}
		}
		
	}
}
#pragma warning restore 1591
