#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class RecordTemplate
	{
		private int _templateID;
		public virtual int TemplateID
		{
			get
			{
				return this._templateID;
			}
			set
			{
				this._templateID = value;
			}
		}
		
		private string _templateName;
		public virtual string TemplateName
		{
			get
			{
				return this._templateName;
			}
			set
			{
				this._templateName = value;
			}
		}
		
		private string _className;
		public virtual string ClassName
		{
			get
			{
				return this._className;
			}
			set
			{
				this._className = value;
			}
		}
		
		private string _status;
		public virtual string Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private bool _bindAct;
		public virtual bool BindAct
		{
			get
			{
				return this._bindAct;
			}
			set
			{
				this._bindAct = value;
			}
		}
		
		private int? _displayOrder;
		public virtual int? DisplayOrder
		{
			get
			{
				return this._displayOrder;
			}
			set
			{
				this._displayOrder = value;
			}
		}
		
		private string _oldVersion;
		public virtual string OldVersion
		{
			get
			{
				return this._oldVersion;
			}
			set
			{
				this._oldVersion = value;
			}
		}
		
		private IList<RecordInstance> _recordInstances = new List<RecordInstance>();
		public virtual IList<RecordInstance> RecordInstances
		{
			get
			{
				return this._recordInstances;
			}
		}
		
	}
}
#pragma warning restore 1591
