#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class RecordInsSignIn
	{
		private string _instanceID;
		public virtual string InstanceID
		{
			get
			{
				return this._instanceID;
			}
			set
			{
				this._instanceID = value;
			}
		}
		
		private string _empCode;
		public virtual string EmpCode
		{
			get
			{
				return this._empCode;
			}
			set
			{
				this._empCode = value;
			}
		}
		
		private DateTime? _signTime;
		public virtual DateTime? SignTime
		{
			get
			{
				return this._signTime;
			}
			set
			{
				this._signTime = value;
			}
		}
		
		private string _signPath;
		public virtual string SignPath
		{
			get
			{
				return this._signPath;
			}
			set
			{
				this._signPath = value;
			}
		}
		
		private string _targetJob;
		public virtual string TargetJob
		{
			get
			{
				return this._targetJob;
			}
			set
			{
				this._targetJob = value;
			}
		}
		
		private string _roleType;
		public virtual string RoleType
		{
			get
			{
				return this._roleType;
			}
			set
			{
				this._roleType = value;
			}
		}
		
		private RecordInstance _recordInstance;
		public virtual RecordInstance RecordInstance
		{
			get
			{
				return this._recordInstance;
			}
			set
			{
				this._recordInstance = value;
			}
		}
		
	}
}
#pragma warning restore 1591
