#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class RecordInsViewer
	{
		private string _instanceID;
		public virtual string InstanceID
		{
			get
			{
				return this._instanceID;
			}
			set
			{
				this._instanceID = value;
			}
		}
		
		private int _viewOrder;
		public virtual int ViewOrder
		{
			get
			{
				return this._viewOrder;
			}
			set
			{
				this._viewOrder = value;
			}
		}
		
		private string _viewer;
		public virtual string Viewer
		{
			get
			{
				return this._viewer;
			}
			set
			{
				this._viewer = value;
			}
		}
		
		private string _viewStatus;
		public virtual string ViewStatus
		{
			get
			{
				return this._viewStatus;
			}
			set
			{
				this._viewStatus = value;
			}
		}
		
		private DateTime? _viewTime;
		public virtual DateTime? ViewTime
		{
			get
			{
				return this._viewTime;
			}
			set
			{
				this._viewTime = value;
			}
		}
		
		private string _viewMemo;
		public virtual string ViewMemo
		{
			get
			{
				return this._viewMemo;
			}
			set
			{
				this._viewMemo = value;
			}
		}
		
		private int _sN;
		public virtual int SN
		{
			get
			{
				return this._sN;
			}
			set
			{
				this._sN = value;
			}
		}
		
		private RecordInstance _recordInstance;
		public virtual RecordInstance RecordInstance
		{
			get
			{
				return this._recordInstance;
			}
			set
			{
				this._recordInstance = value;
			}
		}
		
	}
}
#pragma warning restore 1591
