#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class ScoreInstance
	{
		private string _instanceID;
		public virtual string InstanceID
		{
			get
			{
				return this._instanceID;
			}
			set
			{
				this._instanceID = value;
			}
		}
		
		private string _settingID;
		public virtual string SettingID
		{
			get
			{
				return this._settingID;
			}
			set
			{
				this._settingID = value;
			}
		}
		
		private DateTime _dataSDate;
		public virtual DateTime DataSDate
		{
			get
			{
				return this._dataSDate;
			}
			set
			{
				this._dataSDate = value;
			}
		}
		
		private DateTime _dataEDate;
		public virtual DateTime DataEDate
		{
			get
			{
				return this._dataEDate;
			}
			set
			{
				this._dataEDate = value;
			}
		}
		
		private string _creater;
		public virtual string Creater
		{
			get
			{
				return this._creater;
			}
			set
			{
				this._creater = value;
			}
		}
		
		private DateTime _createDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private DateTime? _modifyDate;
		public virtual DateTime? ModifyDate
		{
			get
			{
				return this._modifyDate;
			}
			set
			{
				this._modifyDate = value;
			}
		}
		
		private string _modifier;
		public virtual string Modifier
		{
			get
			{
				return this._modifier;
			}
			set
			{
				this._modifier = value;
			}
		}
		
		private ScoreSetting _scoreSetting;
		public virtual ScoreSetting ScoreSetting
		{
			get
			{
				return this._scoreSetting;
			}
			set
			{
				this._scoreSetting = value;
			}
		}
		
		private IList<ScoreInstanceDetail> _scoreInstanceDetails = new List<ScoreInstanceDetail>();
		public virtual IList<ScoreInstanceDetail> ScoreInstanceDetails
		{
			get
			{
				return this._scoreInstanceDetails;
			}
		}
		
	}
}
#pragma warning restore 1591
