#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class ScoreSettingDetail
	{
		private string _settingID;
		public virtual string SettingID
		{
			get
			{
				return this._settingID;
			}
			set
			{
				this._settingID = value;
			}
		}
		
		private string _valueType;
		public virtual string ValueType
		{
			get
			{
				return this._valueType;
			}
			set
			{
				this._valueType = value;
			}
		}
		
		private string _valueID;
		public virtual string ValueID
		{
			get
			{
				return this._valueID;
			}
			set
			{
				this._valueID = value;
			}
		}
		
		private string _valueParameter;
		public virtual string ValueParameter
		{
			get
			{
				return this._valueParameter;
			}
			set
			{
				this._valueParameter = value;
			}
		}
		
		private decimal? _scorePercent;
		public virtual decimal? ScorePercent
		{
			get
			{
				return this._scorePercent;
			}
			set
			{
				this._scorePercent = value;
			}
		}
		
		private string _valueName;
		public virtual string ValueName
		{
			get
			{
				return this._valueName;
			}
			set
			{
				this._valueName = value;
			}
		}
		
		private int? _displayOrder;
		public virtual int? DisplayOrder
		{
			get
			{
				return this._displayOrder;
			}
			set
			{
				this._displayOrder = value;
			}
		}
		
		private string _scoreType;
		public virtual string ScoreType
		{
			get
			{
				return this._scoreType;
			}
			set
			{
				this._scoreType = value;
			}
		}
		
		private ScoreSetting _scoreSetting;
		public virtual ScoreSetting ScoreSetting
		{
			get
			{
				return this._scoreSetting;
			}
			set
			{
				this._scoreSetting = value;
			}
		}
		
	}
}
#pragma warning restore 1591
