#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class TeachPointItem
	{
		private int _itemID;
		public virtual int ItemID
		{
			get
			{
				return this._itemID;
			}
			set
			{
				this._itemID = value;
			}
		}
		
		private string _itemName;
		public virtual string ItemName
		{
			get
			{
				return this._itemName;
			}
			set
			{
				this._itemName = value;
			}
		}
		
		private string _itemType;
		public virtual string ItemType
		{
			get
			{
				return this._itemType;
			}
			set
			{
				this._itemType = value;
			}
		}
		
		private string _pointUnit;
		public virtual string PointUnit
		{
			get
			{
				return this._pointUnit;
			}
			set
			{
				this._pointUnit = value;
			}
		}
		
		private decimal? _eachPoint;
		public virtual decimal? EachPoint
		{
			get
			{
				return this._eachPoint;
			}
			set
			{
				this._eachPoint = value;
			}
		}
		
		private string _eachUnit;
		public virtual string EachUnit
		{
			get
			{
				return this._eachUnit;
			}
			set
			{
				this._eachUnit = value;
			}
		}
		
		private decimal? _maxPoint;
		public virtual decimal? MaxPoint
		{
			get
			{
				return this._maxPoint;
			}
			set
			{
				this._maxPoint = value;
			}
		}
		
		private string _maxPointEvalRange;
		public virtual string MaxPointEvalRange
		{
			get
			{
				return this._maxPointEvalRange;
			}
			set
			{
				this._maxPointEvalRange = value;
			}
		}
		
		private string _remark;
		public virtual string Remark
		{
			get
			{
				return this._remark;
			}
			set
			{
				this._remark = value;
			}
		}
		
		private string _trainingType;
		public virtual string TrainingType
		{
			get
			{
				return this._trainingType;
			}
			set
			{
				this._trainingType = value;
			}
		}
		
		private IList<TeachPointRef> _teachPointRefs = new List<TeachPointRef>();
		public virtual IList<TeachPointRef> TeachPointRefs
		{
			get
			{
				return this._teachPointRefs;
			}
		}
		
		private IList<TeachPointItemRequire> _teachPointItemRequires = new List<TeachPointItemRequire>();
		public virtual IList<TeachPointItemRequire> TeachPointItemRequires
		{
			get
			{
				return this._teachPointItemRequires;
			}
		}
		
		private IList<TeachPointEmpItemDatum> _teachPointEmpItemData = new List<TeachPointEmpItemDatum>();
		public virtual IList<TeachPointEmpItemDatum> TeachPointEmpItemData
		{
			get
			{
				return this._teachPointEmpItemData;
			}
		}
		
		private IList<TeachPointCalcTypeRef> _teachPointCalcTypeRefs = new List<TeachPointCalcTypeRef>();
		public virtual IList<TeachPointCalcTypeRef> TeachPointCalcTypeRefs
		{
			get
			{
				return this._teachPointCalcTypeRefs;
			}
		}
		
		private IList<TeachPointJobItem> _teachPointJobItems = new List<TeachPointJobItem>();
		public virtual IList<TeachPointJobItem> TeachPointJobItems
		{
			get
			{
				return this._teachPointJobItems;
			}
		}
		
	}
}
#pragma warning restore 1591
