#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using KMU.EduActivity.DomainModel.Entities;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class TeachPointItemRequire
	{
		private int _itemID;
		public virtual int ItemID
		{
			get
			{
				return this._itemID;
			}
			set
			{
				this._itemID = value;
			}
		}
		
		private string _reqType;
		public virtual string ReqType
		{
			get
			{
				return this._reqType;
			}
			set
			{
				this._reqType = value;
			}
		}
		
		private string _reqID;
		public virtual string ReqID
		{
			get
			{
				return this._reqID;
			}
			set
			{
				this._reqID = value;
			}
		}
		
		private decimal? _reqCount;
		public virtual decimal? ReqCount
		{
			get
			{
				return this._reqCount;
			}
			set
			{
				this._reqCount = value;
			}
		}
		
		private decimal? _reqRate;
		public virtual decimal? ReqRate
		{
			get
			{
				return this._reqRate;
			}
			set
			{
				this._reqRate = value;
			}
		}
		
		private TeachPointItem _teachPointItem;
		public virtual TeachPointItem TeachPointItem
		{
			get
			{
				return this._teachPointItem;
			}
			set
			{
				this._teachPointItem = value;
			}
		}
		
	}
}
#pragma warning restore 1591
