#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class V_hosp
	{
		private string _unitname_all;
		public virtual string Unitname_all
		{
			get
			{
				return this._unitname_all;
			}
			set
			{
				this._unitname_all = value;
			}
		}
		
		private string _unitname;
		public virtual string Unitname
		{
			get
			{
				return this._unitname;
			}
			set
			{
				this._unitname = value;
			}
		}
		
		private string _unitcode;
		public virtual string Unitcode
		{
			get
			{
				return this._unitcode;
			}
			set
			{
				this._unitcode = value;
			}
		}
		
		private int? _seq;
		public virtual int? Seq
		{
			get
			{
				return this._seq;
			}
			set
			{
				this._seq = value;
			}
		}
		
		private System.Nullable<System.Char> _ishosp;
		public virtual System.Nullable<System.Char> Ishosp
		{
			get
			{
				return this._ishosp;
			}
			set
			{
				this._ishosp = value;
			}
		}
		
		private System.Nullable<System.Char> _emp_status;
		public virtual System.Nullable<System.Char> Emp_status
		{
			get
			{
				return this._emp_status;
			}
			set
			{
				this._emp_status = value;
			}
		}
		
		private System.Nullable<System.Char> _active;
		public virtual System.Nullable<System.Char> Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private string _hospshortcode;
		public virtual string Hospshortcode
		{
			get
			{
				return this._hospshortcode;
			}
			set
			{
				this._hospshortcode = value;
			}
		}
		
	}
}
#pragma warning restore 1591
