#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class V_KmuEmp
	{
		private DateTime? _servedate;
		public virtual DateTime? Servedate
		{
			get
			{
				return this._servedate;
			}
			set
			{
				this._servedate = value;
			}
		}
		
		private string _pwd;
		public virtual string Pwd
		{
			get
			{
				return this._pwd;
			}
			set
			{
				this._pwd = value;
			}
		}
		
		private string _loccode;
		public virtual string Loccode
		{
			get
			{
				return this._loccode;
			}
			set
			{
				this._loccode = value;
			}
		}
		
		private string _jobcode;
		public virtual string Jobcode
		{
			get
			{
				return this._jobcode;
			}
			set
			{
				this._jobcode = value;
			}
		}
		
		private string _hospname;
		public virtual string Hospname
		{
			get
			{
				return this._hospname;
			}
			set
			{
				this._hospname = value;
			}
		}
		
		private string _hospcode;
		public virtual string Hospcode
		{
			get
			{
				return this._hospcode;
			}
			set
			{
				this._hospcode = value;
			}
		}
		
		private System.Nullable<System.Char> _groupstatus;
		public virtual System.Nullable<System.Char> Groupstatus
		{
			get
			{
				return this._groupstatus;
			}
			set
			{
				this._groupstatus = value;
			}
		}
		
		private string _groupdept;
		public virtual string Groupdept
		{
			get
			{
				return this._groupdept;
			}
			set
			{
				this._groupdept = value;
			}
		}
		
		private DateTime? _enddate;
		public virtual DateTime? Enddate
		{
			get
			{
				return this._enddate;
			}
			set
			{
				this._enddate = value;
			}
		}
		
		private string _empname;
		public virtual string Empname
		{
			get
			{
				return this._empname;
			}
			set
			{
				this._empname = value;
			}
		}
		
		private string _empcode7;
		public virtual string Empcode7
		{
			get
			{
				return this._empcode7;
			}
			set
			{
				this._empcode7 = value;
			}
		}
		
		private string _empcode;
		public virtual string Empcode
		{
			get
			{
				return this._empcode;
			}
			set
			{
				this._empcode = value;
			}
		}
		
		private string _email;
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				this._email = value;
			}
		}
		
		private string _deptname;
		public virtual string Deptname
		{
			get
			{
				return this._deptname;
			}
			set
			{
				this._deptname = value;
			}
		}
		
		private string _deptcode;
		public virtual string Deptcode
		{
			get
			{
				return this._deptcode;
			}
			set
			{
				this._deptcode = value;
			}
		}
		
		private System.Nullable<System.Char> _nONORG_ID;
		public virtual System.Nullable<System.Char> NONORG_ID
		{
			get
			{
				return this._nONORG_ID;
			}
			set
			{
				this._nONORG_ID = value;
			}
		}
		
		private string _idno;
		public virtual string Idno
		{
			get
			{
				return this._idno;
			}
			set
			{
				this._idno = value;
			}
		}
		
		private string _sCHL_JOB;
		public virtual string SCHL_JOB
		{
			get
			{
				return this._sCHL_JOB;
			}
			set
			{
				this._sCHL_JOB = value;
			}
		}
		
		private string _locname;
		public virtual string Locname
		{
			get
			{
				return this._locname;
			}
			set
			{
				this._locname = value;
			}
		}
		
		private System.Nullable<System.Char> _sEX;
		public virtual System.Nullable<System.Char> SEX
		{
			get
			{
				return this._sEX;
			}
			set
			{
				this._sEX = value;
			}
		}
		
	}
}
#pragma warning restore 1591
