#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class V_kmujob
	{
		private string _jOB_NAME;
		public virtual string JOB_NAME
		{
			get
			{
				return this._jOB_NAME;
			}
			set
			{
				this._jOB_NAME = value;
			}
		}
		
		private string _jOB_KIND_NAME;
		public virtual string JOB_KIND_NAME
		{
			get
			{
				return this._jOB_KIND_NAME;
			}
			set
			{
				this._jOB_KIND_NAME = value;
			}
		}
		
		private System.Nullable<System.Char> _jOB_KIND;
		public virtual System.Nullable<System.Char> JOB_KIND
		{
			get
			{
				return this._jOB_KIND;
			}
			set
			{
				this._jOB_KIND = value;
			}
		}
		
		private string _jOB_DETAIL_NAME;
		public virtual string JOB_DETAIL_NAME
		{
			get
			{
				return this._jOB_DETAIL_NAME;
			}
			set
			{
				this._jOB_DETAIL_NAME = value;
			}
		}
		
		private string _jOB_DETAIL;
		public virtual string JOB_DETAIL
		{
			get
			{
				return this._jOB_DETAIL;
			}
			set
			{
				this._jOB_DETAIL = value;
			}
		}
		
		private string _jOB_CODE_X;
		public virtual string JOB_CODE_X
		{
			get
			{
				return this._jOB_CODE_X;
			}
			set
			{
				this._jOB_CODE_X = value;
			}
		}
		
		private string _eNGLISH_NAME;
		public virtual string ENGLISH_NAME
		{
			get
			{
				return this._eNGLISH_NAME;
			}
			set
			{
				this._eNGLISH_NAME = value;
			}
		}
		
	}
}
#pragma warning restore 1591
