#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class V_KPIRound
	{
		private string _yearCode;
		public virtual string YearCode
		{
			get
			{
				return this._yearCode;
			}
			set
			{
				this._yearCode = value;
			}
		}
		
		private DateTime? _viewDetDeadline;
		public virtual DateTime? ViewDetDeadline
		{
			get
			{
				return this._viewDetDeadline;
			}
			set
			{
				this._viewDetDeadline = value;
			}
		}
		
		private DateTime _updateTime;
		public virtual DateTime UpdateTime
		{
			get
			{
				return this._updateTime;
			}
			set
			{
				this._updateTime = value;
			}
		}
		
		private string _roundCode;
		public virtual string RoundCode
		{
			get
			{
				return this._roundCode;
			}
			set
			{
				this._roundCode = value;
			}
		}
		
		private string _modifier;
		public virtual string Modifier
		{
			get
			{
				return this._modifier;
			}
			set
			{
				this._modifier = value;
			}
		}
		
		private string _hospCode;
		public virtual string HospCode
		{
			get
			{
				return this._hospCode;
			}
			set
			{
				this._hospCode = value;
			}
		}
		
		private string _des;
		public virtual string Des
		{
			get
			{
				return this._des;
			}
			set
			{
				this._des = value;
			}
		}
		
		private DateTime _deadlineStep2;
		public virtual DateTime DeadlineStep2
		{
			get
			{
				return this._deadlineStep2;
			}
			set
			{
				this._deadlineStep2 = value;
			}
		}
		
		private DateTime _deadlineStep1;
		public virtual DateTime DeadlineStep1
		{
			get
			{
				return this._deadlineStep1;
			}
			set
			{
				this._deadlineStep1 = value;
			}
		}
		
		private DateTime _dateTo;
		public virtual DateTime DateTo
		{
			get
			{
				return this._dateTo;
			}
			set
			{
				this._dateTo = value;
			}
		}
		
		private DateTime _dateFrom;
		public virtual DateTime DateFrom
		{
			get
			{
				return this._dateFrom;
			}
			set
			{
				this._dateFrom = value;
			}
		}
		
		private string _creator;
		public virtual string Creator
		{
			get
			{
				return this._creator;
			}
			set
			{
				this._creator = value;
			}
		}
		
	}
}
#pragma warning restore 1591
