#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace KMU.EduActivity.DomainModel.Entities	
{
	public partial class V_KPINorm
	{
		private bool _withFormTyping;
		public virtual bool WithFormTyping
		{
			get
			{
				return this._withFormTyping;
			}
			set
			{
				this._withFormTyping = value;
			}
		}
		
		private bool _withDataImport;
		public virtual bool WithDataImport
		{
			get
			{
				return this._withDataImport;
			}
			set
			{
				this._withDataImport = value;
			}
		}
		
		private string _uploaderDes;
		public virtual string UploaderDes
		{
			get
			{
				return this._uploaderDes;
			}
			set
			{
				this._uploaderDes = value;
			}
		}
		
		private DateTime _updateTime;
		public virtual DateTime UpdateTime
		{
			get
			{
				return this._updateTime;
			}
			set
			{
				this._updateTime = value;
			}
		}
		
		private string _status;
		public virtual string Status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		
		private int _showSeqNo;
		public virtual int ShowSeqNo
		{
			get
			{
				return this._showSeqNo;
			}
			set
			{
				this._showSeqNo = value;
			}
		}
		
		private string _roundCode;
		public virtual string RoundCode
		{
			get
			{
				return this._roundCode;
			}
			set
			{
				this._roundCode = value;
			}
		}
		
		private string _parentKPIID;
		public virtual string ParentKPIID
		{
			get
			{
				return this._parentKPIID;
			}
			set
			{
				this._parentKPIID = value;
			}
		}
		
		private string _normID;
		public virtual string NormID
		{
			get
			{
				return this._normID;
			}
			set
			{
				this._normID = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private string _modifier;
		public virtual string Modifier
		{
			get
			{
				return this._modifier;
			}
			set
			{
				this._modifier = value;
			}
		}
		
		private string _kPIID;
		public virtual string KPIID
		{
			get
			{
				return this._kPIID;
			}
			set
			{
				this._kPIID = value;
			}
		}
		
		private bool _forIndivudual;
		public virtual bool ForIndivudual
		{
			get
			{
				return this._forIndivudual;
			}
			set
			{
				this._forIndivudual = value;
			}
		}
		
		private double _eachScore;
		public virtual double EachScore
		{
			get
			{
				return this._eachScore;
			}
			set
			{
				this._eachScore = value;
			}
		}
		
		private string _eachDes;
		public virtual string EachDes
		{
			get
			{
				return this._eachDes;
			}
			set
			{
				this._eachDes = value;
			}
		}
		
		private string _des;
		public virtual string Des
		{
			get
			{
				return this._des;
			}
			set
			{
				this._des = value;
			}
		}
		
		private string _creator;
		public virtual string Creator
		{
			get
			{
				return this._creator;
			}
			set
			{
				this._creator = value;
			}
		}
		
		private double _ceilingScore;
		public virtual double CeilingScore
		{
			get
			{
				return this._ceilingScore;
			}
			set
			{
				this._ceilingScore = value;
			}
		}
		
	}
}
#pragma warning restore 1591
