<%@ Page Title="" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeFile="PassPortSpecialListSetting.aspx.cs" Inherits="PassPortSpecialListSetting" %>

<%@ Register assembly="Telerik.Web.UI" namespace="Telerik.Web.UI" tagprefix="telerik" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" Runat="Server">
    <asp:Panel ID="Panel1" runat="server">
        <asp:Label ID="Label1" runat="server" Text="職編："></asp:Label>
        <asp:TextBox ID="tbEmpCode" runat="server"></asp:TextBox>
        <asp:Label ID="Label2" runat="server" Text="授權項目："></asp:Label>
        <telerik:RadComboBox ID="rcbItem" Runat="server" Width="250px">
        </telerik:RadComboBox>
        <asp:Label ID="Label3" runat="server" Text="指定開始等級："></asp:Label>
        <telerik:RadComboBox ID="rcbLevel" Runat="server" Width="50px" Culture="zh-TW">
            <Items>
                <telerik:RadComboBoxItem runat="server" Text="I" Value="I" />
                <telerik:RadComboBoxItem runat="server" Text="O" Value="O" />
                <telerik:RadComboBoxItem runat="server" Text="S" Value="S" />
            </Items>
        </telerik:RadComboBox>
        <asp:Button ID="btnAdd" runat="server" OnClick="btnAdd_Click" Text="新增" />
    </asp:Panel>
    <asp:Panel ID="Panel2" runat="server">
        <telerik:RadGrid ID="RadGrid1" runat="server" AutoGenerateColumns="False" CellSpacing="0" Culture="zh-TW" GridLines="None" AutoGenerateDeleteColumn="True" OnDeleteCommand="RadGrid1_DeleteCommand">
            <MasterTableView DataKeyNames="empcode,itemcode">
                <Columns>
                    <telerik:GridBoundColumn DataField="empcode" FilterControlAltText="Filter empcode column" HeaderText="職編" UniqueName="empcode">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="empname" FilterControlAltText="Filter empname column" HeaderText="姓名" UniqueName="empname">
                    </telerik:GridBoundColumn>
                    <telerik:GridBoundColumn DataField="itemname" FilterControlAltText="Filter itemname column" HeaderText="授權項目" UniqueName="itemname">
                    </telerik:GridBoundColumn>
                    <telerik:GridButtonColumn DataTextField="DefaultLevel" FilterControlAltText="Filter DefaultLevel column" HeaderText="指定開始等級" UniqueName="DefaultLevel">
                    </telerik:GridButtonColumn>
                </Columns>
            </MasterTableView>
        </telerik:RadGrid>
    </asp:Panel>
</asp:Content>

